name: Auto Unzip Uploaded ZIP

on:
  push:
    paths:
      - "upload/*.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip all zip files
        run: |
          for zip in upload/*.zip; do
            unzip -o "$zip" -d upload/
            rm "$zip"
          done

      - name: Commit extracted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto unzip uploaded zip"
          git push
